language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
- platformio update
before_script: cd esp32/
script:
- platformio run
before_install:
- openssl aes-256-cbc -K $encrypted_8c33768647f2_key -iv $encrypted_8c33768647f2_iv
  -in ./esp32/src/config.h.enc -out ./esp32/src/config.h -d
